### ISSUE TITLE
Will this be updated?

### ISSUE THREAD

**Issue by The-Nyla** [DJtheRedstoner/betterbarriers#1]
Just wondering if the mod will be updated or if it's abandoned

**Comment by DJtheRedstoner** [comment]
If your interested in support for a newer version I can try to update it. What version are you looking for?

**Comment by The-Nyla** [comment]
1.20.1, the only available equivalent mod needs to be toggled on manually with a keybind and is never on by default so it would be nice to have this for newer versions, thank you!

**Comment by DJtheRedstoner** [comment]
I've tested and the existing 1.19.3 jar works on 1.20.1. I marked it as supported on modrinth.

**Comment by The-Nyla** [comment]
Oh that’s awesome! I probably should have tested that but I just assumed the jar would stop the game and send a “this mod requires version x.x.x” error.
