### ISSUE TITLE
Update Modrinth Version Support #s

### ISSUE THREAD

**Issue by Achim2393** [DJtheRedstoner/betterbarriers#2]
Hey! first and foremost, I wanna say that I love your mod dearly. using it on a large-scale project has made it so much easier, and I cant live without it.

Secondly, I noticed that the latest version does work on 1.20.4, but is not mentioned to be compatible on modrinth. Updating the page to mention its compatibility would fix this. 

Thanks again! :)

**Comment by DJtheRedstoner** [comment]
Thank you for the kind words! I updated the supported versions on modrinth.
